// <auto-generated />
using Importer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Importer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230718025127_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Importer.PecaModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("barras")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("desconto")
                        .HasColumnType("double");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ncm")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("peso_liq")
                        .HasColumnType("double");

                    b.Property<double>("preco_bruto")
                        .HasColumnType("double");

                    b.Property<int>("qtd")
                        .HasColumnType("int");

                    b.Property<string>("unidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("pecas_nova", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
